version: '2'
services:
  db:
    image: 'mysql:latest'
    container_name: mysql-db
    environment:
      - MYSQL_ROOT_PASSWORD=spring
    ports:
      - '3306:3306'
    volumes:
      - 'transformationvol:/var/lib/transformation'
    networks:
      - local
  phpmyadmin:
    image: 'phpmyadmin/phpmyadmin:latest'
    container_name: my-php-myadmin
    ports:
      - '9082:80'
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: spring
    networks:
      - local
  eureka-service:
    build: ./eureka-service
    ports:
      - '8761:8761'
    networks:
      - local
  configserver-service:
    build: ./configserver
    ports:
      - '8046:8046'
    depends_on:
      - eureka-service
      - db
    environment:
      eureka.client.serviceUrl.defaultZone: 'http://eureka-service:8761/eureka'
    networks:
      - local
  oauth2-service:
    build: ./oauth2-service
    ports:
      - '8080:8080'
    depends_on:
      - eureka-service
    environment:
      eureka.client.serviceUrl.defaultZone: 'http://eureka-service:8761/eureka'
    networks:
      - local
  flydubai-service:
    build: ./airline microservices/airline-flydubai-service
    ports:
      - '9095:9095'
    depends_on:
      - eureka-service
      - configserver-service
    environment:
      eureka.client.serviceUrl.defaultZone: 'http://eureka-service:8761/eureka'
    networks:
      - local
  transformation-service:
    build: ./transformation-service
    ports:
      - '8082:8082'
    depends_on:
      - eureka-service
      - oauth2-service
      - flydubai-service
      - db
    environment:
      eureka.client.serviceUrl.defaultZone: 'http://eureka-service:8761/eureka'
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/store
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: spring
    networks:
      - local
  zuul-service:
    build: ./zuul-service
    ports:
      - '8083:8083'
    depends_on:
      - eureka-service
      - transformation-service
      - oauth2-service
      - flydubai-service
    environment:
      eureka.client.serviceUrl.defaultZone: 'http://eureka-service:8761/eureka'
    networks:
      - local

networks:
  local:
    driver: bridge

volumes:
  transformationvol: 

