cloud:
  aws:
    credentials:
      access-key: AKIAVF5MBF6ACCHMQW4S
      secret-key: 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
    region:
      static: us-east-1
    stack:
      auto: false

application:
  bucket:
    name: transformation-files


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

server:
  port: 9090

